<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.cache.interceptor.CacheErrorHandlerTests" tests="9" skipped="0" failures="0" errors="0" timestamp="2020-12-12T06:26:39" hostname="DESKTOP-TMNPDT1" time="0.463">
  <properties/>
  <testcase name="clearFail()" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.199"/>
  <testcase name="evictFail()" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.026"/>
  <testcase name="getFailProperException()" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.032"/>
  <testcase name="putFail()" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.023"/>
  <testcase name="getFail()" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.061"/>
  <testcase name="getAndPutFail()" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.029"/>
  <testcase name="putFailProperException()" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.023"/>
  <testcase name="evictFailProperException()" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.03"/>
  <testcase name="clearFailProperException()" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.033"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
