<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.scheduling.quartz.QuartzSupportTests" tests="16" skipped="8" failures="0" errors="0" timestamp="2020-12-12T06:27:11" hostname="DESKTOP-TMNPDT1" time="3.23">
  <properties/>
  <testcase name="jobDetailWithRunnableInsteadOfJob()" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.001"/>
  <testcase name="schedulerRepositoryExposure()" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.296"/>
  <testcase name="schedulerWithHsqlDataSource()" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="2.216"/>
  <testcase name="schedulerWithQuartzJobBean()" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="multipleSchedulersWithQuartzProperties()" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.03"/>
  <testcase name="multipleSchedulers()" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.396"/>
  <testcase name="schedulerAutoStartupFalse()" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.018"/>
  <testcase name="schedulerWithSpringBeanJobFactoryAndJobSchedulingData()" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="schedulerAccessorBean()" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.001">
    <skipped/>
  </testcase>
  <testcase name="schedulerWithSpringBeanJobFactory()" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="schedulerAutoStartsOnContextRefreshedEventByDefault()" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.005"/>
  <testcase name="schedulerWithTaskExecutor()" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="schedulerWithSpringBeanJobFactoryAndQuartzJobBean()" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="schedulerFactoryBeanWithApplicationContext()" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.261"/>
  <testcase name="twoAnonymousMethodInvokingJobDetailFactoryBeans()" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="schedulerWithSpringBeanJobFactoryAndParamMismatchNotIgnored()" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.0">
    <skipped/>
  </testcase>
  <system-out><![CDATA[14:27:13.703 [scheduler_QuartzSchedulerThread] ERROR o.q.c.ErrorLogger - An error occurred while scanning for the next triggers to fire.
org.quartz.JobPersistenceException: Couldn't acquire next trigger: user lacks privilege or object not found: SCHED_TIME in statement [INSERT INTO QRTZ_FIRED_TRIGGERS (SCHED_NAME, ENTRY_ID, TRIGGER_NAME, TRIGGER_GROUP, INSTANCE_NAME, FIRED_TIME, SCHED_TIME, STATE, JOB_NAME, JOB_GROUP, IS_NONCONCURRENT, REQUESTS_RECOVERY, PRIORITY) VALUES('scheduler', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2923) ~[quartz-2.3.2.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2805) ~[quartz-2.3.2.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2803) ~[quartz-2.3.2.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3864) ~[quartz-2.3.2.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTriggers(JobStoreSupport.java:2802) ~[quartz-2.3.2.jar:?]
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:287) [quartz-2.3.2.jar:?]
Caused by: java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: SCHED_TIME in statement [INSERT INTO QRTZ_FIRED_TRIGGERS (SCHED_NAME, ENTRY_ID, TRIGGER_NAME, TRIGGER_GROUP, INSTANCE_NAME, FIRED_TIME, SCHED_TIME, STATE, JOB_NAME, JOB_GROUP, IS_NONCONCURRENT, REQUESTS_RECOVERY, PRIORITY) VALUES('scheduler', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.<init>(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.jdbc.JDBCConnection.prepareStatement(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at sun.reflect.GeneratedMethodAccessor155.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.invoke(AttributeRestoringConnectionInvocationHandler.java:73) ~[quartz-2.3.2.jar:?]
	at com.sun.proxy.$Proxy81.prepareStatement(Unknown Source) ~[?:?]
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.insertFiredTrigger(StdJDBCDelegate.java:2645) ~[quartz-2.3.2.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2906) ~[quartz-2.3.2.jar:?]
	... 5 more
Caused by: org.hsqldb.HsqlException: user lacks privilege or object not found: SCHED_TIME
	at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.ParserDQL.readSimpleColumnName(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.ParserDQL.readSimpleColumnNames(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.ParserDML.compileInsertStatement(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.ParserCommand.compilePart(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.ParserCommand.compileStatement(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.Session.compileStatement(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.StatementManager.compile(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.Session.execute(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.<init>(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.jdbc.JDBCConnection.prepareStatement(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at sun.reflect.GeneratedMethodAccessor155.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.invoke(AttributeRestoringConnectionInvocationHandler.java:73) ~[quartz-2.3.2.jar:?]
	at com.sun.proxy.$Proxy81.prepareStatement(Unknown Source) ~[?:?]
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.insertFiredTrigger(StdJDBCDelegate.java:2645) ~[quartz-2.3.2.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2906) ~[quartz-2.3.2.jar:?]
	... 5 more
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
